-- CreateEnum
CREATE TYPE "SDGGoal" AS ENUM ('NO_POVERTY', 'ZERO_HUNGER', 'GOOD_HEALTH', 'QUALITY_EDUCATION', 'GENDER_EQUALITY', 'CLEAN_WATER', 'AFFORDABLE_ENERGY', 'DECENT_WORK', 'INDUSTRY_INNOVATION', 'REDUCED_INEQUALITIES', 'SUSTAINABLE_CITIES', 'RESPONSIBLE_CONSUMPTION', 'CLIMATE_ACTION', 'LIFE_BELOW_WATER', 'LIFE_ON_LAND', 'PEACE_JUSTICE', 'PARTNERSHIPS');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "sdgGoals" "SDGGoal"[] DEFAULT ARRAY[]::"SDGGoal"[];
